jobs:
  - job: build
    displayName: Docker build
    continueOnError: false
    steps: 
      # Build image
      - task: Docker@2
        displayName: Build image
        inputs:
          command: build
          dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
          repository: $(imageName)
          tags: |
            $(imageTag)

      # Push to ECR
      - task: ECRPushImage@1
        displayName: Push into ECR
        inputs:
          awsCredentials: $(awsConnection)
          regionName: $(region)
          imageSource: 'imageid'
          sourceImageId: '$(imageName):$(imageTag)'
          repositoryName: '$(repoName)'
          pushTag: '$(imageTag)'
          forceDockerNamingConventions: true
