steps:
  # Terraform plan
  - task: TerraformCLI@2
    displayName: terraform plan
    inputs:
      command: "plan"
      workingDirectory: $(workingDirectory)
      commandOptions: |
        -input=false 
        -out=tf-plan 
        -var "aws_region=$(region)" 
      allowTelemetryCollection: true
      providerServiceAws: $(awsConnection)
      providerAwsRegion: $(region)

  -  task: Bash@2
     displayName: 'Terraform plan'
     inputs:
      scrip : |
        # Source terraform input variables
        source $(Build.SourcesDirectory)/infra/deploy/azure-pipelines/scripts/terraform_input_vars.sh
        # Command
        terraform plan \
        -input=false \
        -out-plan=tf-plan \ 
        $(for key in "${!tf_input_variables[@]}"; do echo -var "\"$key=${tf_input_variables[$key]}\""; done)

  # Terraform apply
  - task: TerraformCLI@2
    displayName: terraform apply
    inputs:
      command: "apply"
      workingDirectory: $(workingDirectory)
      commandOptions: tf-plan
      allowTelemetryCollection: true
      providerServiceAws: $(awsConnection)
      providerAwsRegion: $(region)
