##############################
# DEV YAML DEPLOYMENT MANAGE #
##############################

# Manual trigger
trigger: none

resources:
  - repo: self

variables:
  - template: vars/vars-global.yml
  - template: vars/vars-dev.yml # IMPORTANT
pool:
  name: Default

stages:
  #--------------
  # DOCKER BUILD
  #--------------
  - stage: DockerBuild
    displayName: Docker build and ECR push into $(environment)
    jobs:
      template: jobs/docker-build-push-ecr-jobs.yml

  #------------------
  # TEST/UNIT TESTING
  #------------------

  # - stage: UnitTesting
  #   dependsOn: DockerBuild
  #   displayName: Unit Test
  #   jobs:

  #---------------------
  # TERRAFORM VALIDATION
  #---------------------
  - stage: TerraformValidate
    # dependsOn: UnitTesting
    displayName: Terraform validation
    jobs:
      template: jobs/terraform-validation-jobs.yml
    

  #---------------------
  # TERRAFORM DEPLOYMENT
  #---------------------
  - stage: TerraformDeploy
    dependsOn: TerraformValidate
    displayName: Terraform deployment into $(environment)
    condition: succeeded('TerraformValidate')
    jobs:
      - template: jobs/terraform-deploy-jobs.yml
          

