trigger:
  - main

resources:
  - repo: self

variables:
  - template: vars/global.yml
  - template: vars/dev.yml


stages:
  - stage: TerraformDeployment
    displayName: Deploy infra via Terraform
    jobs:
      - job: Deploy
        displayName: Deploy infra
        pool:
          vmImage: "ubuntu-latest"

        steps:
          # install terraform
          - task: TerraformInstaller@2
            displayName: Install Terraform
            inputs: 
              terraformVersion: 'latest'
          
          # Terraform init
          - task: TerraformCLI@2
            inputs:
              command: 'init'
              workingDirectory: 'infra/setup'
              backendType: 'aws'
              allowTelemetryCollection: true
              backendServiceAws: $(variables.awsConnection)
              backendAwsRegion: $(variables.region)
              backendAwsBucket: $(variables.bucketState)
              backendAwsKey: $(variables.key)

          # Terraform validate
          - task: TerraformCLI@2
            inputs:
              command: 'validate'
              workingDirectory: '/infra/setup'
              allowTelemetryCollection: true
          
          # Terraform plan
          - task: TerraformCLI@2
            inputs:
              command: 'plan'
              workingDirectory: '/infra/setup'
              commandOptions: '-out tf-paln'
              allowTelemetryCollection: true
              providerServiceAws: $(variables.awsConnection)
              providerAwsRegion: $(variables.region)
          # Terraform apply
          - task: TerraformCLI@2
            inputs:
              command: 'apply'
              workingDirectory: '/infra/setup'
              commandOptions: '"tf-plan"'
              allowTelemetryCollection: true
              providerServiceAws: $(variables.awsConnection)
              providerAwsRegion: $(variables.region)
          # Terraform done
          - script: echo "Infrastructure deployment completed."
            displayName: 'Done'
          
