steps:
  # install terraform
  - task: TerraformInstaller@2
    displayName: Install Terraform
    inputs:
      terraformVersion: "latest"

  # Terraform init
  - task: TerraformCLI@2
    displayName: terraform init
    inputs:
      command: "init"
      workingDirectory: $(workingDirectory)
      commandOptions: -input=false -var "aws_region=$(region)"
      backendType: "aws"
      allowTelemetryCollection: true
      backendServiceAws: $(awsConnection)
      backendAwsRegion: $(region)
      backendAwsBucket: $(bucketState)
      backendAwsKey: $(key)
